[theme]
primaryColor = "#00BFFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[global]
hideStreamlitMark = true
